trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  projectSolution: '**/IT_Hardware.sln'
  publishDir: '$(Build.ArtifactStagingDirectory)/publish'

stages:
# ------------------------------
# 1. Build & Test + SonarCloud
# ------------------------------
- stage: BuildAndTest
  displayName: "Build, Test & SonarCloud"
  jobs:
  - job: Build
    steps:
      # Code Checkout
      - checkout: self

      # Dependency Installation
      - task: NuGetToolInstaller@1

      - task: NuGetCommand@2
        inputs:
          restoreSolution: '$(projectSolution)'

      # SonarCloud Prepare
      - task: SonarCloudPrepare@1
        inputs:
          SonarCloud: 'SonarCloudServiceConnection'   # Configure in Service Connections
          organization: 'your-org-name'              # e.g., hriskumar
          scannerMode: 'MSBuild'
          projectKey: 'IT_Asset_HQ-Auth2.0'
          projectName: 'IT_Asset_HQ-Auth2.0'

      # Build
      - task: DotNetCoreCLI@2
        displayName: "Build"
        inputs:
          command: 'build'
          projects: '$(projectSolution)'
          arguments: '--configuration $(buildConfiguration)'

      # Unit Tests
      - task: DotNetCoreCLI@2
        displayName: "Run Tests"
        inputs:
          command: 'test'
          projects: '**/*Tests.csproj'
          arguments: '--configuration $(buildConfiguration) --no-build'

      # SonarCloud Analyze
      - task: SonarCloudAnalyze@1

      # SonarCloud Publish
      - task: SonarCloudPublish@1
        inputs:
          pollingTimeoutSec: '300'

# ------------------------------
# 2. Package & Publish Artifacts
# ------------------------------
- stage: Package
  displayName: "Package & Publish"
  dependsOn: BuildAndTest
  jobs:
  - job: PackageJob
    steps:
      - task: DotNetCoreCLI@2
        displayName: "Publish"
        inputs:
          command: 'publish'
          projects: '$(projectSolution)'
          arguments: '--configuration $(buildConfiguration) --output $(publishDir)'

      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: '$(publishDir)'
          artifactName: 'drop'
          publishLocation: 'Container'

# ------------------------------
# 3. Deploy to Azure (staging)
# ------------------------------
- stage: Deploy
  displayName: "Deploy to Azure App Service"
  dependsOn: Package
  jobs:
  - deployment: DeployWeb
    environment: 'stag
